# aiport_data.py
# Complete Southwest Airlines Airport List (2025)
# Extracted from Airport Information _ Southwest Airlines.html

from core.models import Airport

airports = [
    {'city': 'Albany', 'state': 'NY', 'airport': 'Albany International', 'iata': 'ALB'},
    {'city': 'Albuquerque', 'state': 'NM', 'airport': 'Albuquerque International Sunport', 'iata': 'ABQ'},
    {'city': 'Amarillo', 'state': 'TX', 'airport': 'Rick Husband Amarillo International', 'iata': 'AMA'},
    {'city': 'Anchorage', 'state': 'AK', 'airport': 'Ted Stevens Anchorage International', 'iata': 'ANC'},
    {'city': 'Aruba', 'state': 'Aruba', 'airport': 'Queen Beatrix International', 'iata': 'AUA'},
    {'city': 'Atlanta', 'state': 'GA', 'airport': 'Hartsfield—Jackson Atlanta International', 'iata': 'ATL'},
    {'city': 'Austin', 'state': 'TX', 'airport': 'Austin—Bergstrom International', 'iata': 'AUS'},
    {'city': 'Baltimore/Washington', 'state': 'MD', 'airport': 'Baltimore/Washington International Thurgood Marshall', 'iata': 'BWI'},
    {'city': 'Belize City', 'state': 'Belize', 'airport': 'Philip S.W. Goldson International', 'iata': 'BZE'},
    {'city': 'Birmingham', 'state': 'AL', 'airport': 'Birmingham—Shuttlesworth International', 'iata': 'BHM'},
    {'city': 'Boise', 'state': 'ID', 'airport': 'Boise Airport', 'iata': 'BOI'},
    {'city': 'Boston (Logan)', 'state': 'MA', 'airport': 'Logan International', 'iata': 'BOS'},
    {'city': 'Bozeman/Yellowstone', 'state': 'MT', 'airport': 'Bozeman Yellowstone International', 'iata': 'BZN'},
    {'city': 'Buffalo/Niagara', 'state': 'NY', 'airport': 'Buffalo Niagara International', 'iata': 'BUF'},
    {'city': 'Burbank', 'state': 'CA', 'airport': 'Hollywood Burbank', 'iata': 'BUR'},
    {'city': 'Cabo San Lucas', 'state': 'Mexico', 'airport': 'Los Cabos International', 'iata': 'SJD'},
    {'city': 'Cancun', 'state': 'Mexico', 'airport': 'Cancún International', 'iata': 'CUN'},
    {'city': 'Charleston', 'state': 'SC', 'airport': 'Charleston International', 'iata': 'CHS'},
    {'city': 'Charlotte', 'state': 'NC', 'airport': 'Charlotte Douglas International', 'iata': 'CLT'},
    {'city': 'Chicago (Midway)', 'state': 'IL', 'airport': 'Chicago Midway International', 'iata': 'MDW'},
    {'city': 'Chicago (O\'Hare)', 'state': 'IL', 'airport': 'Chicago O\'Hare International', 'iata': 'ORD'},
    {'city': 'Cincinnati', 'state': 'OH', 'airport': 'Cincinnati/Northern Kentucky International', 'iata': 'CVG'},
    {'city': 'Cleveland', 'state': 'OH', 'airport': 'Cleveland Hopkins International', 'iata': 'CLE'},
    {'city': 'Colorado Springs', 'state': 'CO', 'airport': 'Colorado Springs Airport', 'iata': 'COS'},
    {'city': 'Columbus', 'state': 'OH', 'airport': 'John Glenn Columbus International', 'iata': 'CMH'},
    {'city': 'Corpus Christi', 'state': 'TX', 'airport': 'Corpus Christi International', 'iata': 'CRP'},
    {'city': 'Cozumel', 'state': 'Mexico', 'airport': 'Cozumel International', 'iata': 'CZM'},
    {'city': 'Dallas (Love Field)', 'state': 'TX', 'airport': 'Dallas Love Field', 'iata': 'DAL'},
    {'city': 'Denver', 'state': 'CO', 'airport': 'Denver International', 'iata': 'DEN'},
    {'city': 'Des Moines', 'state': 'IA', 'airport': 'Des Moines International', 'iata': 'DSM'},
    {'city': 'Detroit', 'state': 'MI', 'airport': 'Detroit Metropolitan Wayne County', 'iata': 'DTW'},
    {'city': 'El Paso', 'state': 'TX', 'airport': 'El Paso International', 'iata': 'ELP'},
    {'city': 'Fargo', 'state': 'ND', 'airport': 'Hector International', 'iata': 'FAR'},
    {'city': 'Fort Lauderdale', 'state': 'FL', 'airport': 'Fort Lauderdale—Hollywood International', 'iata': 'FLL'},
    {'city': 'Fort Myers', 'state': 'FL', 'airport': 'Southwest Florida International', 'iata': 'RSW'},
    {'city': 'Fresno', 'state': 'CA', 'airport': 'Fresno Yosemite International', 'iata': 'FAT'},
    {'city': 'Grand Cayman', 'state': 'Cayman Islands', 'airport': 'Owen Roberts International', 'iata': 'GCM'},
    {'city': 'Grand Rapids', 'state': 'MI', 'airport': 'Gerald R. Ford International', 'iata': 'GRR'},
    {'city': 'Greenville/Spartanburg', 'state': 'SC', 'airport': 'Greenville—Spartanburg International', 'iata': 'GSP'},
    {'city': 'Guadalajara', 'state': 'Mexico', 'airport': 'Miguel Hidalgo y Costilla Guadalajara International', 'iata': 'GDL'},
    {'city': 'Harlingen', 'state': 'TX', 'airport': 'Valley International', 'iata': 'HRL'},
    {'city': 'Hartford/Springfield', 'state': 'CT', 'airport': 'Bradley International', 'iata': 'BDL'},
    {'city': 'Havana', 'state': 'Cuba', 'airport': 'José Martí International', 'iata': 'HAV'},
    {'city': 'Honolulu', 'state': 'HI', 'airport': 'Daniel K. Inouye International', 'iata': 'HNL'},
    {'city': 'Houston (Hobby)', 'state': 'TX', 'airport': 'William P. Hobby', 'iata': 'HOU'},
    {'city': 'Houston (Intercontinental)', 'state': 'TX', 'airport': 'George Bush Intercontinental', 'iata': 'IAH'},
    {'city': 'Indianapolis', 'state': 'IN', 'airport': 'Indianapolis International', 'iata': 'IND'},
    {'city': 'Ixtapa/Zihuatanejo', 'state': 'Mexico', 'airport': 'Ixtapa-Zihuatanejo International', 'iata': 'ZIH'},
    {'city': 'Jacksonville', 'state': 'FL', 'airport': 'Jacksonville International', 'iata': 'JAX'},
    {'city': 'Kahului', 'state': 'HI', 'airport': 'Kahului Airport', 'iata': 'OGG'},
    {'city': 'Kansas City', 'state': 'MO', 'airport': 'Kansas City International', 'iata': 'MCI'},
    {'city': 'Kauai (Lihue)', 'state': 'HI', 'airport': 'Lihue Airport', 'iata': 'LIH'},
    {'city': 'Kona', 'state': 'HI', 'airport': 'Ellison Onizuka Kona International', 'iata': 'KOA'},
    {'city': 'Knoxville', 'state': 'TN', 'airport': 'McGhee Tyson', 'iata': 'TYS'},
    {'city': 'Las Vegas', 'state': 'NV', 'airport': 'Harry Reid International', 'iata': 'LAS'},
    {'city': 'Leon/Guanajuato', 'state': 'Mexico', 'airport': 'Del Bajío International', 'iata': 'BJX'},
    {'city': 'Liberia', 'state': 'Costa Rica', 'airport': 'Daniel Oduber Quirós International', 'iata': 'LIR'},
    {'city': 'Little Rock', 'state': 'AR', 'airport': 'Bill and Hillary Clinton National', 'iata': 'LIT'},
    {'city': 'Long Beach', 'state': 'CA', 'airport': 'Long Beach Airport', 'iata': 'LGB'},
    {'city': 'Los Angeles (LAX)', 'state': 'CA', 'airport': 'Los Angeles International', 'iata': 'LAX'},
    {'city': 'Los Cabos', 'state': 'Mexico', 'airport': 'Los Cabos International', 'iata': 'SJD'},
    {'city': 'Louisville', 'state': 'KY', 'airport': 'Louisville Muhammad Ali International', 'iata': 'SDF'},
    {'city': 'Lubbock', 'state': 'TX', 'airport': 'Lubbock Preston Smith International', 'iata': 'LBB'},
    {'city': 'Manzanillo', 'state': 'Mexico', 'airport': 'Playa de Oro International', 'iata': 'ZLO'},
    {'city': 'Manchester', 'state': 'NH', 'airport': 'Manchester—Boston Regional', 'iata': 'MHT'},
    {'city': 'Mazatlan', 'state': 'Mexico', 'airport': 'General Rafael Buelna International', 'iata': 'MZT'},
    {'city': 'Memphis', 'state': 'TN', 'airport': 'Memphis International', 'iata': 'MEM'},
    {'city': 'Mexico City', 'state': 'Mexico', 'airport': 'Mexico City International', 'iata': 'MEX'},
    {'city': 'Miami', 'state': 'FL', 'airport': 'Miami International', 'iata': 'MIA'},
    {'city': 'Midland/Odessa', 'state': 'TX', 'airport': 'Midland International Air & Space Port', 'iata': 'MAF'},
    {'city': 'Milwaukee', 'state': 'WI', 'airport': 'General Mitchell International', 'iata': 'MKE'},
    {'city': 'Minneapolis/St. Paul', 'state': 'MN', 'airport': 'Minneapolis—Saint Paul International', 'iata': 'MSP'},
    {'city': 'Montego Bay', 'state': 'Jamaica', 'airport': 'Sangster International', 'iata': 'MBJ'},
    {'city': 'Monterrey', 'state': 'Mexico', 'airport': 'General Mariano Escobedo International', 'iata': 'MTY'},
    {'city': 'Myrtle Beach', 'state': 'SC', 'airport': 'Myrtle Beach International', 'iata': 'MYR'},
    {'city': 'Nashville', 'state': 'TN', 'airport': 'Nashville International', 'iata': 'BNA'},
    {'city': 'Nassau', 'state': 'Bahamas', 'airport': 'Lynden Pindling International', 'iata': 'NAS'},
    {'city': 'New Orleans', 'state': 'LA', 'airport': 'Louis Armstrong New Orleans International', 'iata': 'MSY'},
    {'city': 'New York (LaGuardia)', 'state': 'NY', 'airport': 'LaGuardia (New York)', 'iata': 'LGA'},
    {'city': 'Newark', 'state': 'NJ', 'airport': 'Newark Liberty International', 'iata': 'EWR'},
    {'city': 'Norfolk', 'state': 'VA', 'airport': 'Norfolk International', 'iata': 'ORF'},
    {'city': 'Oakland', 'state': 'CA', 'airport': 'Oakland International', 'iata': 'OAK'},
    {'city': 'Oklahoma City', 'state': 'OK', 'airport': 'Will Rogers World', 'iata': 'OKC'},
    {'city': 'Omaha', 'state': 'NE', 'airport': 'Eppley Airfield', 'iata': 'OMA'},
    {'city': 'Ontario/San Bernardino', 'state': 'CA', 'airport': 'Ontario International', 'iata': 'ONT'},
    {'city': 'Orange County', 'state': 'CA', 'airport': 'John Wayne Airport', 'iata': 'SNA'},
    {'city': 'Orlando', 'state': 'FL', 'airport': 'Orlando International', 'iata': 'MCO'},
    {'city': 'Panama City', 'state': 'Panama', 'airport': 'Tocumen International', 'iata': 'PTY'},
    {'city': 'Panama City Beach', 'state': 'FL', 'airport': 'Northwest Florida Beaches International', 'iata': 'ECP'},
    {'city': 'Pensacola', 'state': 'FL', 'airport': 'Pensacola International', 'iata': 'PNS'},
    {'city': 'Philadelphia', 'state': 'PA', 'airport': 'Philadelphia International', 'iata': 'PHL'},
    {'city': 'Phoenix', 'state': 'AZ', 'airport': 'Phoenix Sky Harbor International', 'iata': 'PHX'},
    {'city': 'Pittsburgh', 'state': 'PA', 'airport': 'Pittsburgh International', 'iata': 'PIT'},
    {'city': 'Portland', 'state': 'OR', 'airport': 'Portland International', 'iata': 'PDX'},
    {'city': 'Providence', 'state': 'RI', 'airport': 'Rhode Island T.F. Green International', 'iata': 'PVD'},
    {'city': 'Puerto Vallarta', 'state': 'Mexico', 'airport': 'Licenciado Gustavo Díaz Ordaz International', 'iata': 'PVR'},
    {'city': 'Punta Cana', 'state': 'Dominican Republic', 'airport': 'Punta Cana International', 'iata': 'PUJ'},
    {'city': 'Raleigh/Durham', 'state': 'NC', 'airport': 'Raleigh—Durham International', 'iata': 'RDU'},
    {'city': 'Reno/Tahoe', 'state': 'NV', 'airport': 'Reno—Tahoe International', 'iata': 'RNO'},
    {'city': 'Richmond', 'state': 'VA', 'airport': 'Richmond International', 'iata': 'RIC'},
    {'city': 'Rochester', 'state': 'NY', 'airport': 'Frederick Douglass—Greater Rochester International', 'iata': 'ROC'},
    {'city': 'Sacramento', 'state': 'CA', 'airport': 'Sacramento International', 'iata': 'SMF'},
    {'city': 'Salt Lake City', 'state': 'UT', 'airport': 'Salt Lake City International', 'iata': 'SLC'},
    {'city': 'San Antonio', 'state': 'TX', 'airport': 'San Antonio International', 'iata': 'SAT'},
    {'city': 'San Diego', 'state': 'CA', 'airport': 'San Diego International', 'iata': 'SAN'},
    {'city': 'San Francisco', 'state': 'CA', 'airport': 'San Francisco International', 'iata': 'SFO'},
    {'city': 'San Jose', 'state': 'CA', 'airport': 'Norman Y. Mineta San José International', 'iata': 'SJC'},
    {'city': 'San Jose', 'state': 'Costa Rica', 'airport': 'Juan Santamaría International', 'iata': 'SJO'},
    {'city': 'San Juan', 'state': 'PR', 'airport': 'Luis Muñoz Marín International', 'iata': 'SJU'},
    {'city': 'San Luis Potosí', 'state': 'Mexico', 'airport': 'Ponciano Arriaga International', 'iata': 'SLP'},
    {'city': 'Santa Ana/Orange County', 'state': 'CA', 'airport': 'John Wayne Airport', 'iata': 'SNA'},
    {'city': 'Santa Barbara', 'state': 'CA', 'airport': 'Santa Barbara Municipal', 'iata': 'SBA'},
    {'city': 'Sarasota/Bradenton', 'state': 'FL', 'airport': 'Sarasota—Bradenton International', 'iata': 'SRQ'},
    {'city': 'Seattle/Tacoma', 'state': 'WA', 'airport': 'Seattle—Tacoma International', 'iata': 'SEA'},
    {'city': 'Spokane', 'state': 'WA', 'airport': 'Spokane International', 'iata': 'GEG'},
    {'city': 'St. Louis', 'state': 'MO', 'airport': 'St. Louis Lambert International', 'iata': 'STL'},
    {'city': 'Syracuse', 'state': 'NY', 'airport': 'Syracuse Hancock International', 'iata': 'SYR'},
    {'city': 'Tampa', 'state': 'FL', 'airport': 'Tampa International', 'iata': 'TPA'},
    {'city': 'Tucson', 'state': 'AZ', 'airport': 'Tucson International', 'iata': 'TUS'},
    {'city': 'Tulsa', 'state': 'OK', 'airport': 'Tulsa International', 'iata': 'TUL'},
    {'city': 'Turks and Caicos', 'state': 'Turks and Caicos', 'airport': 'Providenciales International', 'iata': 'PLS'},
    {'city': 'Washington (DCA)', 'state': 'DC', 'airport': 'Ronald Reagan Washington National', 'iata': 'DCA'},
    {'city': 'Washington (IAD)', 'state': 'VA', 'airport': 'Washington Dulles International', 'iata': 'IAD'},
    {'city': 'West Palm Beach', 'state': 'FL', 'airport': 'Palm Beach International', 'iata': 'PBI'},
    {'city': 'Kahului (Maui)', 'state': 'HI', 'airport': 'Kahului Airport', 'iata': 'OGG'},
    {'city': 'Hilo', 'state': 'HI', 'airport': 'Hilo International Airport', 'iata': 'ITO'},
    {'city': 'Kailua-Kona', 'state': 'HI', 'airport': 'Ellison Onizuka Kona International Airport at Keāhole', 'iata': 'PHKO'},
    {'city': 'Honolulu (Oahu)', 'state': 'HI', 'airport': 'Daniel K. Inouye International', 'iata': 'HNL'},
    {'city': 'Lihue (Kauai)', 'state': 'HI', 'airport': 'Lihue Airport', 'iata': 'LIH'},
]

def find_airport(input_term):
    """
    Find an airport by IATA code, city name, or airport name.
    
    Args:
        input_term: Search string (IATA code, city, or airport name)
    
    Returns:
        Dictionary with airport info if found, None otherwise
    """
    term = input_term.strip().lower()
    
    for airport in airports:
        if (airport['iata'].lower() == term or
            term in airport['city'].lower() or
            term in airport['airport'].lower()):
            return Airport(**airport)
    
    return None

